### ISSUE TITLE
ERROR: StatusCode: ResourceExhausted, Detail: "Quota exceeded."

### ISSUE THREAD

**Issue by cuonglee** [stevecox1964/WinRecognize#2]
My code works fine, but to day, when i run, i get this error. My quotas dashboard is empty and my voice file size is very small (about 150 kb).  Please tell me what happend, and what can i do to fix it.

Screen shot for detail:
http://prntscr.com/hn8pep

Thank you in advance.

**Comment by stevecox1964** [comment]
Keep in mind that the Google api has a limit on how many speech to text
conversions are aloud per day. I don't know right off hand what the limit
is, but
you maybe running up against it here.

Thank

Steve

**Comment by cuonglee** [comment]
I have fixed it.
I used the license for demo, replace it with my registed key make my program works. Thank you.
